### ISSUE TITLE
V3 roadmap

### ISSUE THREAD

**Issue by alex38160** [Perpetual-Altruism-Ltd/myNFT-Bridge#36]
Here is a list of the issues defining the next release :

- [ ] Professional redesign of the UI
- [ ] Prevent the relay to start the migration process if metadata and image can't be accessed
- [ ] Manage the case where image field in metadata is a video
- [ ] #32 
- [ ] ERC 1155 support and/or Full migration
- [ ] Bridge external integration
